### ISSUE TITLE
bug: Can not deloy token

### ISSUE THREAD

**Issue by cuongnmftu1** [kkrt-labs/kakarot-rpc#1199]
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at importCsjOrEsModule (/root/kakarot-erc20/node_modules/hardhat/src/internal/core/config/config-loading.ts:29:22)
    at loadConfigAndTasks (/root/kakarot-erc20/node_modules/hardhat/src/internal/core/config/config-loading.ts:95:18)
    at main (/root/kakarot-erc20/node_modules/hardhat/src/internal/cli/cli.ts:218:62)

**Comment by bajpai244** [comment]
@cuongnmftu1 can you share some information on how can replicate this?

+ this seems to be more of a node issue and not something coming from the network, but feel free to share how we can replicate this!

**Comment by swetshaw** [comment]
@cuongnmftu1  Here's the GitHub repository for the tutorial  — https://github.com/Karrot-Works/erc20-tutorial. You can check it out and raise issues there

**Comment by greged93** [comment]
hey all, I'm closing this as it seems to come from a node issue and we don't have any news. Don't hesitate to reopen @cuongnmftu1 if this ends up being an issue from our side.
